version: '3.7'

services:
  db:
    image: postgres
    ports:
      - 8181:5432
    volumes:
    - db-storage:/var/lib/postgresql/data/
    env_file:
      - ./.env.database

volumes:
  db-storage:
    external: true